### PR TITLE
Configurable builder

### PR DESCRIPTION
**Pull request by flocsy**
To enable creating custom CurlBuilders (for https://github.com/mrmike/Ok2Curl/issues)

    public static class MyCurlInterceptor extends CurlInterceptor {
        private static final int[] PARTS_ORDER = new int[]{
                ConfigurableCurlBuilder.PART_CURL,
                ConfigurableCurlBuilder.PART_OPTIONS,
                ConfigurableCurlBuilder.PART_METHOD,
                ConfigurableCurlBuilder.PART_URL,
                ConfigurableCurlBuilder.PART_BODY,
                ConfigurableCurlBuilder.PART_CONTENT_TYPE,
                ConfigurableCurlBuilder.PART_HEADERS
        };

        public MyCurlInterceptor(Loggable logger) {
            super(logger);
        }

        @Override
        protected CurlBuilder getCurlBuilder(Request copy) {
            return new ConfigurableCurlBuilder(copy, limit, headerModifiers, options, delimiter, PARTS_ORDER);
        }
    }

Let me know what do you think. I think it can also be merged into CurlBuilder, since we have a default order so we can move all the code in ConfigurableCurlBuilder into CurlBuilder

### CODE REVIEW

**Comment by C2H6O** [comment]
@flocsy any reason not to merge this in?

**Comment by flocsy** [comment]
you can merge IMHO

**Comment by mrmike** [comment]
LGTM 👍

**Comment by sergeidyga** [comment]
Hi Michał! Thank you for your explanation 🙂 now I see.

**Pull request merged**
